version: 2
jobs:
  build:
    branches:
      ignore:
        - gh-pages

    docker:
      - image: circleci/node:8.10

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-

      - run: sudo npm i -g npm@6.1

      - run: npm ci

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: npm test

      - run: npm run build

      - deploy:
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              echo "$DOMAIN" > public/CNAME
              cp -r .circleci public/.circleci
              git config --global user.email "$GH_EMAIL"
              git config --global user.name "$GH_NAME"
              NODE_DEBUG=gh-pages npm run publish -- -m 'automated build'
            else
              echo "Not master branch so not deploying"
            fi
